apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-qa
- name: scgskku/shortener-fe-qa
  newTag: 123eec481ad988d93047d9dac5efe8bd4c1c9973
