apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-qa
- name: scgskku/shortener-fe-qa
  newTag: 9d29a85c9c9d04c37229e567c36564f2f0784431
