apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

patches:
- path: domain.json
  target:
    kind: Ingress
    name: shortener-api-ingress

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-qa
- name: scgskku/shortener-api-qa
  newTag: d451a4cd26f94c24c53e905b6a2c3a8b21d197b4
