apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

patches:
- path: domain.json
  target:
    kind: Ingress
    name: shortener-api-ingress

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-qa
- name: scgskku/shortener-api-qa
  newTag: a1575e6b956ba568c38f8cf70cd8abd4a6f9de28
