apiVersion: v1
kind: Secret
metadata:
  name: shortener-secret
  annotations:
    avp.kubernetes.io/path: kv/data/shortener
type: Opaque
data:
  DATABASE_URL: <path:kv/data/shortener#database-url-qa | base64encode>
  DATABASE_USERNAME: <path:kv/data/shortener#db-user-qa | base64encode>
  DATABASE_PASSWORD: <path:kv/data/shortener#db-password-qa | base64encode>
  JWT_SECRET: <path:kv/data/shortener#jwt-qa | base64encode>
  BASE_URL: <path:kv/data/shortener#base-url-qa | base64encode>
