apiVersion: v1
kind: Secret
metadata:
  name: shortener-secret
  annotations:
    avp.kubernetes.io/path: kv/data/shortener
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: <path:kv/data/shortener#SPRING_DATASOURCE-url-qa>
  SPRING_DATASOURCE_USERNAME: <path:kv/data/shortener#db-user-qa>
  SPRING_DATASOURCE_PASSWORD: <path:kv/data/shortener#db-password-qa>
  SPRING_PROFILES_ACTIVE: dev
