apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- ../../../base/fe

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-prod
- name: scgskku/shortener-fe-prod
  newTag: 076ebc0ffe1f4034b7c04765a6d0d90c06717a78
