apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- ../../../base/fe

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-prod
- name: scgskku/shortener-fe-prod
  newTag: d6049f4e71614392fdb46e33deb6e8d97f6850d0
