apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- ../../../base/fe

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-prod
- name: scgskku/shortener-fe-prod
  newTag: 51c7150a758f59c9f32d6a9681d458eb63168305
