apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-prod
- name: scgskku/shortener-api-prod
  newTag: ac668dcc3b546072a51c4d3a9ca861a0213aa290
