apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-prod
- name: scgskku/shortener-api-prod
  newTag: 179cefda0ac34d14d72be493635726b166d1c293
