apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-prod
- name: scgskku/shortener-api-prod
  newTag: 7d0292f4a306431768f26c5050fbf754a6982018
