apiVersion: v1
kind: Secret
metadata:
  name: shortener-secret
  annotations:
    avp.kubernetes.io/path: kv/data/shortener-secret
type: Opaque
data:
  DATABASE_URL: <path:kv/data/shortener-secret#database-url-prod | base64encode>
  DATABASE_USERNAME: <path:kv/data/shortener-secret#db-user-prod | base64encode>
  DATABASE_PASSWORD: <path:kv/data/shortener-secret#db-password-prod | base64encode>
  JWT_SECRET: <path:kv/data/shortener-secret#jwt-secret-prod | base64encode>
  BASE_URL: <path:kv/data/shortener-secret#base-url-prod | base64encode>
